# -*- fill-column: 76; -*-
#+Title: Benchmarks for Espressobin driver mvneta
#+AUTHOR: Jesper Dangaard Brouer
#+EMAIL: brouer@redhat.com
#+OPTIONS: ^:nil

This document focus on benchmarking the patchset from Lorenzo Bianconi
 - [[https://patchwork.ozlabs.org/project/netdev/list/?series=134430&state=%2a][Patchset V1]]
 - Message-Id: <cover.1570307172.git.lorenzo@kernel.org>
 - Thread on [[https://lore.kernel.org/netdev/cover.1570307172.git.lorenzo@kernel.org/][lore.kernel.org]]

The patchset adds XDP support to the Marvell driver mvneta.

The benchmark will be performed on a [[https://espressobin.net/][EspressoBin]] board.

* Code being tested

Due to some adjustment to patchset V1, that involved DMA-sync to-device,
which is *VERY* expensive on this board, I've decided to create a separate
branch on a git tree (under my control), to keep this reproducible.

In flux Lorenzo GitHub tree with mvneta developement is here:
- https://github.com/LorenzoBianconi/net-next/tree/mvneta-devel

More stable tree with patches I've tested:
- TODO create branch on
- https://git.kernel.org/pub/scm/linux/kernel/git/hawk/net-next-xdp.git/
- xdp_mvneta01

* Initial benchmark notes

#+begin_example
root@espressobin:~/samples/bpf# ./xdp1 3
proto 0:     420389 pkt/s
proto 0:     421554 pkt/s
proto 0:     421760 pkt/s
#+end_example

* Extra: Config settings

Enable kernel config setting: =CONFIG_ARM64_PSEUDO_NMI=

I've not setup the kernel parameter "irqchip.gicv3_pseudo_nmi" to 1, but I
want to have the option to enable this, as this allow for better perf
reports.

See why in Kernel-Recipes 2019 talk:
- [[https://kernel-recipes.org/en/2019/talks/no-nmi-no-problem-implementing-arm64-pseudo-nmi/][Implementing Arm64 Pseudo-NMI]]


