#+TITLE: People involved in XDP development

* Intro

Lets record people involved on XDP development.
Need this to Cc the right people on the mailing list.

* History

The early "moonshot" ideas behind having a step before allocating the
SKB, was presented by Jesper at NetDev 1.1 (Feb 2016), who also did
PoC experiments (with mlx5) extrapolating a performance could reach
19Mpps per core. Today we are seeing between 16Mpps to 24Mpps per core
depending on which NIC HW used (mlx5 driver).

 http://people.netfilter.org/hawk/presentations/NetDev1.1_2016/net_performance_BoF.pdf

The initial XDP patchset was developed by:
 Brenden Blanco <bblanco@gmail.com> / <bblanco@vmware.com>
After this Brenden have not been active developing XDP.

The XDP name was coined by Tom Herbert.  Tom Herbert and Alexei
Starovoitov did the first presentation about XDP, while both working
for Facebook.

 https://github.com/iovisor/bpf-docs/blob/master/Express_Data_Path.pdf

* XDP developers

eBPF maintainers:
- Alexei Starovoitov
- Daniel Borkmann

Core XDP developers:
- Brenden Blanco <bblanco@gmail.com> (initial XDP patchset)
- Tom Herbert <tom@herbertland.com> (coined XDP)
- John Fastabend <john.fastabend@gmail.com>
- Jakub Kicinski <jakub.kicinski@netronome.com> (netronome + core work)
- Quentin Monnet <quentin.monnet@netronome.com> (netronome + core work)
- David Ahern (fib lookup helper)
- Jesper Brouer <brouer@redhat.com>
- Toke Høiland-Jørgensen <toke@redhat.com>

eBPF core developers influencing XDP:
- Martin KaFai Lau <kafai@fb.com>

Driver developers:
- Andy Gospodarek (bnxt_en + presentations)
- Michael Chan (bnxt_en)
- Saeed Mahameed (mlx5)
- Tariq Toukan (mlx4)
- Björn Töpel (i40e + ixgbe + AF_XDP)
- Magnus Karlsson (i40e + AF_XDP)
- Yuval Mintz (qede)
- Sunil Goutham (thunderx)
- Jason Wang (VM)
- Michael S. Tsirkin (ptr_ring)
- Edward Cree (sfc)
- Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp> (veth)
- Ilias Apalodimas <ilias.apalodimas@linaro.org> (netsec)

Developers unsorted:
- PJ (still waiting for data_meta work)

* Working groups

** page_pool

Proposal for evolving API see: [[file:areas/mem/page_pool01_evolving_API.org]]

People interested in working on page_pool API:
 - Tariq Toukan <tariqt@mellanox.com> / <ttoukan.linux@gmail.com>
 - Ilias Apalodimas <ilias.apalodimas@linaro.org>

Potential people interested:
 - Willy Tarreau <w@1wt.eu>
 - mykyta.iziumtsev@gmail.com (Ericsson engineer)
 - ard.biesheuvel@linaro.org (from Linaro)

People to keep in loop:
 - Toke
 - Andy Gospodarek <gospo@broadcom.com>
 - Daniel
 - Alexei?

Drivers that will get XDP and use page_pool:
 - driver: mlx5
 - driver: mvpp2  board: Macchiatobin
 - driver: mvneta board: espressobin + Turris-Omnia

Drivers with XDP and page_pool usage:
 - driver: netsec board: Socionext DeveloperBox
