#+TITLE: Identify XDP issues

* Issue: Missing update of ifconfig counters

Some drivers are not updating the "ifconfig" stats counters,
when in XDP mode.  This makes receive or send via XDP invisible to
sysadm/management tools.  This for-sure is going to cause confusion.

Closer look at other drivers.

 - ixgbe driver is doing the right thing.

 - i40e have a bug, where RX/TX stats are swapped (strange!).

 - mlx5 driver is not updating the regular RX/TX counters, but A LOT
   of other ethtool stats counters (which are the ones I usually
   monitor when testing).

Need to have an upstream discussion, on what is the semantic.  IHMO
the regular RX/TX counters must be updated even for XDP frames.


* Issue: XDP_REDIRECT is few drivers

Very few drivers support XDP_REDIRECT.

HW drivers: ixgbe, i40e, mlx5

SW drivers: veth, tun (tuntap), virtio_net


** Status: Supported XDP drivers

Slide with overview of drivers


* Issue: ndo_xdp_xmit bound to XDP_REDIRECT

Driver resources needed to handle a ndo_xdp_xmit() is currently tied
to the driver having loaded an RX XDP program. This is strange, as
allocating these Driver TX HW resources is independend.

This can quickly lead to exhausting HW resources, like IRQs lines or
NIC TX HW queues, given it is assumed a TX queue is alloc/dedicated
for each CPU core.


* Issue: usability of xdp_redirect + xdp_redirect_map

The samples/bpf programs xdp_redirect + xdp_redirect_map are very user
unfriendly.  #1 they use raw ifindex'es as input + output. #2 the
pkt/s number count RX packets, not TX'ed packets which can be dropped
silently.

Red Hat QA, got very confused by #2.

