#+Title: XDP-hints via kfuncs: For driver igc

* Driver: igc

I implemented metadata XDP hints kfuncs in driver igc.
As this hardware supports timestamping.

** Driver igc: list timestamp types

The tcpdump tool can be used for listing the NICs timestamp types:

#+begin_src sh
$ tcpdump -i igc1 --list-time-stamp-types
Time stamp types for igc1 (use option -j to set):
  host (Host)
  adapter_unsynced (Adapter, not synced with system time)
#+end_src

** Driver igc: Initial test#1 with igc

Selftest tool "xdp_hw_metadata" have HW timestamp enable features, but it
doesn't seem to work in igc hardware.

#+begin_example
sudo ./xdp_hw_metadata igc1
[...]
xsk_ring_cons__peek: 1
0x1c52958: rx_desc[0]->addr=100000000008000 addr=8100 comp_addr=8000
rx_hash: 0x00000000
rx_timestamp:  0 (sec:0.0000)
0x1c52958: complete idx=8 addr=8000
#+end_example

Using tcpdump to enable HW timestamp on NIC:
 - tcpdump -ni igc1 -j adapter_unsynced

Now we have timestamps:
#+begin_example
xsk_ring_cons__peek: 1
0x164c958: rx_desc[1]->addr=100000000009000 addr=9100 comp_addr=9000
rx_hash: 0x00000000
rx_timestamp:  1676296571376017676 (sec:1676296571.3760)
XDP RX-time:   1676296608373030219 (sec:1676296608.3730) delta sec:36.9970
AF_XDP time:   1676296608373128431 (sec:1676296608.3731) delta sec:0.0001 (98.212 usec)
0x164c958: complete idx=9 addr=9000
#+end_example

The HW "rx_timestamp" is clearly not in sync with system time. The XDP-RX and
AF_XDP time in about comes from =CLOCK_TAI= clock-id, which currently have an
offset of 37 seconds to wall-clock time. Given the delta is below 37 sec
(sec:36.9970) it seems XDP RX-time happened *before* the packet was received by
hardware, which obviously isn't possible (without a time machine).

** Driver igc: RX-hash broken for netstack

The driver contains code for RX-hash extract, but the net_device NETIF_F_RXHASH
feature bit isn't set. This also makes it impossible to enable manually via
ethtool.

#+begin_example
$ ethtool -k igc1 | grep hash
receive-hashing: off [fixed]
#+end_example

Since: 0507ef8a0372 ("igc: Add transmit and receive fastpath and interrupt handlers")
 - $ git describe --contains  0507ef8a0372
 - v4.20-rc1~27^2~40^2~5

Git commit history and fix commit message:

#+begin_quote
When function igc_rx_hash() was introduced in v4.20 via commit 0507ef8a0372
("igc: Add transmit and receive fastpath and interrupt handlers"), the
hardware wasn't configured to provide RSS hash, thus it made sense to not
enable net_device NETIF_F_RXHASH feature bit.

The NIC hardware was configured to enable RSS hash info in v5.2 via commit
2121c2712f82 ("igc: Add multiple receive queues control supporting"), but
forgot to set the NETIF_F_RXHASH feature bit.

The original implementation of igc_rx_hash() didn't extract the associated
pkt_hash_type, but statically set PKT_HASH_TYPE_L3. The largest portions of
this patch are about extracting the RSS Type from the hardware and mapping
this to enum pkt_hash_types. This were based on Foxville i225 software user
manual rev-1.3.1 and tested on Intel Ethernet Controller I225-LM (rev 03).

For UDP it's worth noting that RSS (type) hashing have been disabled both for
IPv4 and IPv6 (see IGC_MRQC_RSS_FIELD_IPV4_UDP + IGC_MRQC_RSS_FIELD_IPV6_UDP)
because hardware RSS doesn't handle fragmented pkts well when enabled (can
cause out-of-order). This result in PKT_HASH_TYPE_L3 for UDP packets, and
hash value doesn't include UDP port numbers. Not being PKT_HASH_TYPE_L4, have
the effect that netstack will do a software based hash calc calling into
flow_dissect, but only when code calls skb_get_hash(), which doesn't
necessary happen for local delivery.

Fixes: 2121c2712f82 ("igc: Add multiple receive queues control supporting")
#+end_quote

