# FIXME: This should be more generic and included everywhere; but works for now

BUILD_SCRIPT := ../emacs.d/build-slides.sh

all: xdp-distro-view.html

xdp-distro-view.html: xdp-distro-view.org
	$(BUILD_SCRIPT) xdp-distro-view.org
