# -*- fill-column: 76; -*-
#+Title: NXP LS1088A - notes
#+OPTIONS: ^:nil

Board LS1088ARDB-PB.
- SoC: LS1088AE Rev1.0 (0x87030010)

* Boot another kernel

Trick to temporarily boot another kernel.

Copy over kernel to SD-card (while Linux is running on board):
#+begin_example
rsync -av arch/arm64/boot/Image root@192.168.42.10:/boot/Image2
#+end_example

During power up break into U-Boot:
#+begin_example
setenv kernel_image Image2
boot
#+end_example

This works because the board have a U-Boot script =ls1088ardb_boot.scr= that
use variable =kernel_image=, if set, else it fallback to =Image= (which
refer to =/boot/Image= under Linux).

* Boot issue (and workaround) above kernel v5.1

ARM changed the behavior on SMMU devices (IOMMU), which seems this device
have not caught up with. (Likely in this commit [[https://git.kernel.org/torvalds/c/v5.2-rc1~83^2^4~1^2~11][v5.2-rc1~83^2^4~1^2~11]]).

Error messages in dmesg looks like this:
#+begin_example
 arm-smmu 5000000.iommu: Unexpected global fault, this could be serious
 arm-smmu 5000000.iommu:  GFSR 0x80000002, GFSYNR0 0x00000002
#+end_example

*** Boot workaround on v5.2 and above

There is a kernel boot parameter =arm-smmu.disable_bypass=0= that disable
this behaviour (allowing insecure mode).

Fortunately this board have a bootscript 'ls1088ardb_boot.scr', which allows
easy addition of extra boot args via U-Boot env 'othbootargs':

#+begin_src sh
 setenv othbootargs arm-smmu.disable_bypass=0
#+end_src

* Kernel config adjustments

Platform selection:
- CONFIG_ARCH_LAYERSCAPE: "ARMv8 based Freescale Layerscape SoC family"

Config adjustments:
- CONFIG_MMC_SDHCI_OF_ESDHC: "SDHCI OF support for the Freescale eSDHC controller"
- CONFIG_FSL_MC_BUS=y  : "QorIQ DPAA2 fsl-mc bus driver"
- CONFIG_FSL_MC_DPIO=y : "QorIQ DPAA2 DPIO driver"
- CONFIG_FSL_GUTS=y (selected by others)
- CONFIG_PHY_FSL_IMX8MQ_USB: "Freescale i.MX8M USB3 PHY"
- CONFIG_NET_VENDOR_FREESCALE=y
- CONFIG_FSL_DPAA2_ETH : "Freescale DPAA2 Ethernet"
- CONFIG_FSL_DPAA2: "Freescale DPAA2 devices"
- CONFIG_FSL_DPAA2_ETHSW: "Freescale DPAA2 Ethernet Switch"
- CONFIG_PCI_LAYERSCAPE: "Freescale Layerscape PCIe controller"
- CONFIG_PCI_LAYERSCAPE=y
- CONFIG_SOC_BUS=y

